### ISSUE TITLE
Multiple NDB Issues.

### ISSUE THREAD

**Issue by SynecticLabs** [Outpost-System/Outpost#4]
We're currently unable to persist the NDB settings through sessions. No errors are being returned. Anybody available to look into it, please?

**Comment by ronh3** [comment]
Created configs for NDB (colors, which orgs are enemies, etc) and saved with ndb save. Quit out (which showed NDB configs being saved again), closed, reopened profile, settings loaded in just fine. Are the NDB persistence issues above due to just closing the mud/Mudlet without saving NDB configs first?

**Comment by SynecticLabs** [comment]
I'm getting this: https://ada-young.com/pastebin/jLCZEbFE

**Comment by SynecticLabs** [comment]
Are we missing the execution of tempTrigger() assignation? It's making no attempt to grab the API data for those names, so they are in existence.

**Comment by SynecticLabs** [comment]
'qw update' fixes the issue. I'll add as a workaround for now.

**Comment by SynecticLabs** [comment]
https://ada-young.com/pastebin/ct7vhPhl

**Comment by ronh3** [comment]
Not sure if it's going to be an issue here, since I went through ndb.lua to look around at things, but I know there were issues with a few ndb type things when Lusternia added non-binary as gender. May be worth looking into.

**Comment by SynecticLabs** [comment]
Nope, nothing there was causing the issue, but I have located the problem. Will commit a fix soon.

**Comment by SynecticLabs** [comment]
Closing. Issue resolved.
